/*
 * Arcaea excavation notebook
 * Section 06: LogicArcTapNote placement, input, judgement, and parent-Arc modes
 *
 * STATUS: ArcTap gameplay slice complete
 * STYLE: C++-like pseudocode, NOT recovered source code
 *
 * Evidence terminology:
 *   CONFIRMED     = directly supported by native code/data/control flow.
 *   RECONSTRUCTED = readable representation assembled from confirmed behaviour.
 *   UNRESOLVED    = exact semantic name/purpose is not yet proved.
 *
 * Scope of this section:
 *   - how ArcTap timestamps are evaluated on the parent Arc path
 *   - where the resulting ArcTap gameplay position is cached
 *   - how a touch becomes an ArcTap candidate
 *   - how ArcTap reuses LogicTapNote timing judgement
 *   - how ArcTap success and LOST enter ScoreState
 *   - how parent Arc +0xA4 modes affect ArcTap and Arc-body judgement
 *   - whether parent-Arc hold/contact is required
 *
 * Deliberately out of scope:
 *   - ArcTap rendering, textures, particles, and meshes
 *   - exact final camera-scaled hit-region dimensions
 *   - full camera/timinggroup architecture
 *   - exact higher-level semantic name of Arc mode value 2
 *
 * This file builds directly on:
 *   02_note_fundamentals.cpp
 *   04_arc_contact.cpp
 *   05_arc_path.cpp
 *
 * Useful native anchors from the investigated ARM64 build:
 *   point-note judgement candidate             ~0x160CE28
 *   GameModel touch-begin candidate builder    ~0x0EEC024
 *   candidate-list time sort                    ~0x0F6B514
 *   ArcTap successful-hit override             ~0x0C78814
 *   ArcTap LOST override                       ~0x178F5FC
 *   common gameplay / automatic-miss loop      ~0x0F8056C
 *   Arc runtime initialiser / child promotion  ~0x0C664F8
 *   Arc sampled-path / ArcTap placement builder~0x1925084
 *   common camera-scaled hit-region helper     ~0x0927384
 *
 * WARNING ABOUT SYMBOLS:
 * The binary is stripped. Readable names below are reconstruction names unless
 * explicitly described as surviving RTTI/type names or confirmed chart fields.
 */

#include <algorithm>
#include <cstdint>
#include <vector>

// -----------------------------------------------------------------------------
// 1. Runtime inheritance: ArcTap is a point note, not a long-note body event
// -----------------------------------------------------------------------------

/*
 * CONFIRMED RTTI:
 *
 *   LogicNote
 *      |
 *      +-- LogicTapNote
 *             |
 *             +-- LogicArcTapNote
 *
 * This remains one of the most important architectural facts:
 *
 *   Arc BODY  -> LogicLongNoteBase repeated-event machinery
 *   ArcTap    -> LogicTapNote one-shot timing judgement machinery
 *
 * A LogicArcNote owns a vector of attached LogicArcTapNote pointers around
 * LogicArcNote +0x120, but ownership does not turn those children into long
 * note ticks.
 */
struct LogicNote;
struct LogicTapNote;
struct LogicArcNote;
struct LogicArcTapNote;
struct ScoreState;
struct GameModel;
struct TouchRecord;

// -----------------------------------------------------------------------------
// 2. Selected ArcTap fields
// -----------------------------------------------------------------------------

/*
 * CONFIRMED selected fields:
 *
 *   inherited +0x0C : local LOST flag
 *   inherited +0x0D : local successful-hit flag
 *   inherited +0x10 : secondary hit/input payload, established in Section 02
 *   inherited +0x18 : start timestamp
 *   inherited +0x1C : end timestamp
 *
 * LogicTapNote makes startTime == endTime, so ArcTap is likewise a point event.
 *
 *   +0x80..+0x8B : 12-byte cached path position generated by the parent Arc
 *                   path builder. Same Vec3-like size/layout family used by
 *                   Section 05's sampled Arc path data.
 *
 *   +0x90       : pointer consulted by ArcTap-specific success/LOST hooks.
 *                 The pointed object is read at +0xA4, whose behaviour matches
 *                 the owning LogicArcNote's established mode field.
 *
 * The semantic name parentArc for +0x90 is RECONSTRUCTED, strongly supported by:
 *   - LogicArcNote owning ArcTap children at +0x120
 *   - ArcTap hooks consulting the owning Arc mode field
 *   - parent path construction writing each child's +0x80 cached position
 *
 * The exact assignment site for +0x90 has not yet been isolated, so the member
 * name itself is not labelled CONFIRMED original source terminology.
 */
struct ArcTapPathPoint {
    float component0;
    float component1;
    float component2;
};
static_assert(sizeof(ArcTapPathPoint) == 12);

struct LogicTapNote {
    bool lost;                 // readable representation of +0x0C
    bool hit;                  // +0x0D
    int32_t inputPayload;      // +0x10, exact higher-level name unresolved
    int32_t startTimeMs;       // +0x18
    int32_t endTimeMs;         // +0x1C
};

struct LogicArcTapNote : LogicTapNote {
    ArcTapPathPoint cachedPathPoint; // +0x80
    LogicArcNote* parentArc;         // +0x90, RECONSTRUCTED member name

    // A string-like object begins around +0x98 and participates in extra
    // feedback/audio behaviour on successful hits. Its exact gameplay semantic
    // purpose is UNRESOLVED and not required for judgement reconstruction.
};

// -----------------------------------------------------------------------------
// 3. ArcTap timestamp -> normalized parent-Arc progress
// -----------------------------------------------------------------------------

/*
 * CONFIRMED in the Arc path builder around ~0x1925084.
 *
 * The parent LogicArcNote iterates its child vector at +0x120 and evaluates each
 * ArcTap at the child's point timestamp.
 *
 * The normalized progress is mechanically:
 *
 *   t = (arcTapTime - parentArcStart)
 *       / (effectivePathEnd - parentArcStart)
 *
 * In the ordinary case effectivePathEnd == parentArc.endTime.
 *
 * Section 05 established one wrinkle: a related-pointer vector around parent
 * +0x138 can extend effectivePathEnd to the maximum of the Arc's own end time
 * and selected related objects' start times. The exact semantic identity of
 * that related-vector remains UNRESOLVED.
 *
 * Therefore do NOT simplify the native builder universally to denominator
 * parent.endTime-parent.startTime, although that is the normal case.
 */
float normalizedArcTapProgress(
    const LogicArcNote& parent,
    const LogicArcTapNote& tap,
    int32_t effectivePathEndMs)
{
    return float(tap.startTimeMs - parent.startTimeMs)
         / float(effectivePathEndMs - parent.startTimeMs);
}

// -----------------------------------------------------------------------------
// 4. ArcTap position is evaluated by the SAME parent Arc easing machinery
// -----------------------------------------------------------------------------

/*
 * CONFIRMED:
 *
 * After calculating normalized t, the path builder dispatches through the same
 * easing branch established in Section 05:
 *
 *   s / b / si / so / sisi / sosi / siso / soso
 *
 * `b` uses the dedicated cubic helper.
 * The other classic types use the straight/sinusoidal evaluator.
 *
 * The resulting 12-byte Vec3-like value is copied directly into:
 *
 *   ArcTap +0x80 .. +0x8B
 *
 * Representative native stores are equivalent to:
 *
 *   *(uint64_t*)(tap + 0x80) = result.firstEightBytes;
 *   *(uint32_t*)(tap + 0x88) = result.lastFourBytes;
 *
 * This is a precomputed spatial placement. Touch-begin later consumes this
 * cached point rather than rerunning AFF easing from scratch.
 */
ArcTapPathPoint evaluateArcTapPoint(
    const LogicArcNote& parent,
    int32_t arcTapTimeMs,
    int32_t effectivePathEndMs)
{
    const float t =
        float(arcTapTimeMs - parent.startTimeMs)
        / float(effectivePathEndMs - parent.startTimeMs);

    return evaluateParentArcPath(parent, t); // Section 05 formulas
}

void cacheArcTapPoints(LogicArcNote& parent, int32_t effectivePathEndMs)
{
    for (LogicArcTapNote* tap : parent.arcTaps) {
        tap->cachedPathPoint =
            evaluateArcTapPoint(parent, tap->startTimeMs, effectivePathEndMs);
    }
}

// -----------------------------------------------------------------------------
// 5. Touch-begin builds a spatially filtered point-note candidate list
// -----------------------------------------------------------------------------

/*
 * CONFIRMED GameModel architecture around ~0x0EEC024.
 *
 * GameModel maintains a top-level active-note collection around +0xA0 and a
 * temporary candidate vector around +0xB8.
 *
 * On touch-begin, the candidate vector is first cleared. GameModel walks active
 * notes and handles note families differently:
 *
 *   ordinary LogicTapNote:
 *       filter using its lane/input identity
 *
 *   LogicHoldNote:
 *       filter using lane/input identity and Hold timing/contact conditions
 *
 *   LogicArcNote:
 *       iterate the parent's ArcTap vector at +0x120
 *       spatially test each ArcTap child
 *       push the ArcTap CHILD into the temporary candidate vector if qualified
 *
 * Therefore ArcTap does NOT enter the ordinary lane-note branch as an independent
 * top-level note. It is discovered spatially through its parent Arc.
 */

// The temporary vector insertion helper is a normal pointer-vector push_back.
void addCandidate(std::vector<LogicNote*>& candidates, LogicNote* note)
{
    candidates.push_back(note);
}

// -----------------------------------------------------------------------------
// 6. ArcTap has a real sky/gameplay-space hit-region gate
// -----------------------------------------------------------------------------

/*
 * CONFIRMED touch-begin ArcTap filtering:
 *
 * For each child in LogicArcNote +0x120, GameModel:
 *   - copies the child's cached 12-byte point from +0x80
 *   - combines it with the parent Arc's gameplay horizontal anchor/transform
 *   - transforms current touch coordinates into the same gameplay-space frame
 *   - calls the common camera-scaled hit-region helper around ~0x0927384
 *
 * The helper receives:
 *
 *   nominal size value = 212.0f
 *   mode flag          = 1 for ArcTap
 *
 * Section 04's ordinary Arc-body contact calls the SAME helper with mode flag 0.
 * The mode flag alters internal bound construction, so this file deliberately
 * does NOT claim that final ArcTap and Arc-body rectangles are identical.
 *
 * The safe gameplay statement is:
 *
 *   ArcTap must be spatially near its precomputed point in sky/gameplay space
 *   before it is allowed into the timing-candidate list.
 *
 * It is NOT merely "any touch anywhere at the correct timestamp".
 */
bool spatiallyQualifiesArcTap(
    GameModel& game,
    const TouchRecord& touch,
    LogicArcNote& parent,
    LogicArcTapNote& tap)
{
    const auto expected =
        convertArcTapCachedPointToHitTestPoint(parent, tap.cachedPathPoint);

    const auto finger = transformTouchToGameplaySpace(game, touch);

    return cameraScaledHitRegionTest(
        game,
        finger,
        expected,
        212.0f,
        /* arcTapMode */ true);
}

// -----------------------------------------------------------------------------
// 7. Candidate ordering is by note timestamp
// -----------------------------------------------------------------------------

/*
 * CONFIRMED:
 * Before trying the temporary candidates, GameModel sorts the pointer vector.
 * The comparator repeatedly reads note +0x18 and orders by start timestamp.
 *
 * GameModel then walks the sorted candidates. A candidate dynamically castable
 * to LogicTapNote is passed directly to the point-note timing routine around
 * ~0x160CE28. Processing stops when that routine reports that the touch was
 * consumed/accepted as a timing attempt.
 *
 * ArcTap inherits LogicTapNote, so no ArcTap-specific timing-candidate function
 * is inserted between candidate selection and point judgement.
 */
void processTouchCandidates(
    GameModel& game,
    std::vector<LogicNote*>& candidates,
    int touchId)
{
    std::sort(candidates.begin(), candidates.end(),
        [](LogicNote* a, LogicNote* b) {
            return a->startTimeMs < b->startTimeMs;
        });

    for (LogicNote* note : candidates) {
        if (LogicTapNote* tap = dynamic_cast<LogicTapNote*>(note)) {
            if (tryJudgePointNote(game, *tap, touchId)) {
                return;
            }
        }

        // Hold-specific handling follows if the tap cast did not handle it.
    }
}

// -----------------------------------------------------------------------------
// 8. ArcTap inherits the exact point-note timing candidate routine
// -----------------------------------------------------------------------------

/*
 * CONFIRMED direct call path:
 *
 *   spatially-qualified ArcTap
 *       -> temporary candidate vector
 *       -> dynamic_cast<LogicTapNote*>
 *       -> point judgement routine ~0x160CE28
 *
 * Therefore the Section 02 timing arithmetic applies unchanged:
 *
 *   absolute error 0..25 ms   -> judgement 0, MAX PURE
 *   absolute error 26..50 ms  -> judgement 1, PURE
 *   absolute error 51..100 ms -> judgement 2, FAR
 *   absolute error 101..120ms -> ScoreState LOST path
 *   beyond 120 ms             -> this input-candidate routine rejects attempt
 *
 * PURE/FAR use the same reconstructed Early/Late side value as ordinary taps.
 * MAX PURE uses side 0.
 *
 * The inherited prechecks are likewise unchanged:
 *   - ArcTap own LOST flag at +0x0C must be clear
 *   - ArcTap own hit flag at +0x0D must be clear
 *
 * No parent Arc contact byte (+0x64) is read anywhere in this routine.
 */

// -----------------------------------------------------------------------------
// 9. ArcTap overrides successful-hit acceptance
// -----------------------------------------------------------------------------

/*
 * CONFIRMED ArcTap virtual override around ~0x0C78814.
 *
 * After optional feedback/audio work that is outside this gameplay slice, the
 * hook does the same essential local resolution as LogicTapNote:
 *
 *   ArcTap +0x0D = 1
 *   ArcTap +0x10 = input payload/touch identifier
 *
 * It then consults the object at +0x90 and reads that object's +0xA4 mode.
 *
 *   no parent pointer      -> accept
 *   parent mode != 2       -> accept
 *   parent mode == 2       -> veto ScoreState acceptance
 *
 * IMPORTANT ordering:
 * Local ArcTap hit state is written BEFORE the mode-2 veto is returned.
 * Therefore mode 2 resolves the ArcTap locally but prevents ScoreState from
 * treating that local hit as a score/gauge judgement.
 */
bool LogicArcTapNote_acceptSuccessfulHit(
    LogicArcTapNote& tap,
    int judgementTimeMs,
    int inputPayload)
{
    (void)judgementTimeMs;

    // Optional ArcTap feedback/audio path omitted.

    tap.hit = true;
    tap.inputPayload = inputPayload;

    if (tap.parentArc == nullptr) {
        return true;
    }

    return tap.parentArc->arcBodyMode != 2;
}

// -----------------------------------------------------------------------------
// 10. ScoreState path is otherwise the ordinary point-note path
// -----------------------------------------------------------------------------

/*
 * CONFIRMED from Section 02 and the ArcTap override:
 *
 * ScoreState successful judgement:
 *   1. invokes the note's successful-hit virtual
 *   2. if the hook returns false, ScoreState stops before counters/gauge fan-out
 *   3. otherwise increments MAX PURE/PURE/FAR counters normally
 *   4. forwards the judgement to every LifeBarState
 *
 * Thus modes 0/1 use ordinary point-note scoring.
 * Mode 2 locally resolves the child but suppresses ScoreState scoring/gauge work.
 */

// -----------------------------------------------------------------------------
// 11. ArcTap overrides LOST acceptance symmetrically
// -----------------------------------------------------------------------------

/*
 * CONFIRMED ArcTap LOST override around ~0x178F5FC:
 *
 *   ArcTap +0x0C = 1
 *
 * then:
 *
 *   no parent pointer      -> accept LOST
 *   parent mode != 2       -> accept LOST
 *   parent mode == 2       -> veto ScoreState LOST
 *
 * Again, the local resolved-by-miss flag is written before the veto.
 */
bool LogicArcTapNote_acceptLost(LogicArcTapNote& tap)
{
    tap.lost = true;

    if (tap.parentArc == nullptr) {
        return true;
    }

    return tap.parentArc->arcBodyMode != 2;
}

// -----------------------------------------------------------------------------
// 12. Automatic ArcTap miss scheduling is parent-Arc-owned
// -----------------------------------------------------------------------------

/*
 * CONFIRMED in the common gameplay update around ~0x0F8056C.
 *
 * After identifying a LogicArcNote, the update explicitly walks:
 *
 *   Arc +0x120 child vector
 *
 * For each ArcTap child:
 *   - call inherited virtual LOST-flag predicate
 *   - call inherited virtual hit-flag predicate
 *   - skip already resolved children
 *   - compare effective gameplay time against child endTime + 100 ms
 *
 * If:
 *
 *   effectiveTime > arcTap.endTime + 100
 *
 * it calls the ordinary ScoreState LOST entry path for that ArcTap child.
 *
 * Since LogicTapNote uses startTime == endTime, this is conceptually:
 *
 *   effectiveTime > arcTapTime + 100 ms
 *
 * The comparison is strictly greater-than at this scheduling branch.
 *
 * This also sharpens Section 02's timing caveat: the point-input routine has a
 * 101..120 ms LOST candidate band, while normal gameplay scheduling can already
 * auto-LOST an unresolved ArcTap once update time is later than +100 ms.
 * Exact event/update ordering determines whether every theoretical late-side
 * input value is reachable in every frame situation.
 */
void updateArcTapAutomaticMisses(
    GameModel& game,
    LogicArcNote& parent,
    int effectiveTimeMs,
    ScoreState& score)
{
    for (LogicArcTapNote* tap : parent.arcTaps) {
        if (tap->lost || tap->hit) {
            continue;
        }

        if (effectiveTimeMs > tap->endTimeMs + 100) {
            registerLost(score, *tap, effectiveTimeMs);
        }
    }
}

// -----------------------------------------------------------------------------
// 13. Parent Arc +0xA4 is a three-state gameplay mode, not merely a bool
// -----------------------------------------------------------------------------

/*
 * CROSS-SECTION REFINEMENT OF SECTION 04.
 *
 * Section 04 correctly established:
 *   - Arc body geometric contact rejects any +0xA4 != 0
 *   - Arc no-contact long-event predicate returns true only for +0xA4 == 0
 *
 * Therefore body behaviour remains:
 *
 *   mode 0 -> ordinary judged Arc body
 *   mode 1 -> non-body-judged Arc
 *   mode 2 -> non-body-judged Arc
 *
 * NEW CONFIRMED result from this ArcTap excavation:
 *
 * Arc initialisation copies the supplied child vector into Arc +0x120.
 * If the initially supplied mode is 0 AND that child vector is non-empty, the
 * runtime explicitly promotes:
 *
 *   Arc +0xA4 = 1
 *
 * In other words, ArcTap ownership itself forces the parent out of ordinary
 * judged-body mode.
 *
 * Representative readable reconstruction:
 */
enum class ArcBodyMode : int32_t {
    JudgedBody = 0,
    NonJudgedBodyWithJudgedArcTaps = 1, // readable behavioural name
    NonJudgedBodyAndSuppressedArcTaps = 2, // readable behavioural name
};

void initialiseArcChildMode(LogicArcNote& arc, int suppliedMode)
{
    arc.arcBodyMode = suppliedMode;

    if (arc.arcBodyMode == 0 && !arc.arcTaps.empty()) {
        arc.arcBodyMode = 1;
    }
}

/*
 * The enum member names above are RECONSTRUCTED behavioural labels, not original
 * source names. In particular, the complete higher-level reason mode 2 exists is
 * still UNRESOLVED.
 */

// -----------------------------------------------------------------------------
// 14. What classic AFF trace means for ArcTap gameplay
// -----------------------------------------------------------------------------

/*
 * CONFIRMED / strongly tied to chart structure from Section 04:
 * The classic AFF argument after the Arc effect string feeds this +0xA4 mode.
 * A normal boolean true supplies the non-zero trace/non-body-judged state.
 *
 * ArcTap-specific consequence now proven:
 *
 *   mode 1:
 *       parent body is not judged as an ordinary Arc body
 *       ArcTap children are still judged/scored normally
 *
 *   mode 2:
 *       parent body is not judged
 *       ArcTap success hook returns false to ScoreState
 *       ArcTap LOST hook returns false to ScoreState
 *       ArcTap still locally resolves as hit or lost
 *
 * Also, a mode-0 Arc created with ArcTap children is automatically promoted to
 * mode 1. Therefore a normal ArcTap-bearing parent does not remain an ordinary
 * body-contact Arc after runtime initialisation.
 */

// -----------------------------------------------------------------------------
// 15. Parent Arc does NOT need to be currently held for ArcTap judgement
// -----------------------------------------------------------------------------

/*
 * CONFIRMED by converging control flow, not merely by absence of one check:
 *
 *   1. ArcTap candidate selection uses ArcTap spatial position, not parent +0x64.
 *   2. Point timing routine checks ArcTap's own hit/lost state and timestamp.
 *   3. ArcTap successful-hit hook checks parent +0xA4 mode, not contact +0x64.
 *   4. ArcTap LOST hook checks parent +0xA4 mode, not contact +0x64.
 *   5. Runtime automatically moves an Arc with children from body mode 0 to 1,
 *      and mode 1 disables ordinary Arc-body contact/LOST judgement anyway.
 *
 * Therefore the correct gameplay model is:
 *
 *   ArcTap = independent point judgement spatially positioned by a parent path.
 *
 * NOT:
 *
 *   ArcTap = tick which succeeds only while that same parent Arc is held.
 */

// -----------------------------------------------------------------------------
// 16. Readable end-to-end reconstruction
// -----------------------------------------------------------------------------

void onTouchBegin(GameModel& game, const TouchRecord& touch)
{
    std::vector<LogicNote*> candidates;

    for (LogicNote* topLevel : game.activeNotes) {
        if (!topLevel->isActiveForInput) {
            continue;
        }

        if (auto* tap = dynamic_cast<LogicTapNote*>(topLevel)) {
            if (ordinaryLaneTapMatchesTouch(game, touch, *tap)) {
                candidates.push_back(tap);
            }
            continue;
        }

        if (auto* hold = dynamic_cast<LogicHoldNote*>(topLevel)) {
            if (holdAcquisitionMatchesTouch(game, touch, *hold)) {
                candidates.push_back(hold);
            }
            continue;
        }

        if (auto* arc = dynamic_cast<LogicArcNote*>(topLevel)) {
            for (LogicArcTapNote* arcTap : arc->arcTaps) {
                if (spatiallyQualifiesArcTap(game, touch, *arc, *arcTap)) {
                    candidates.push_back(arcTap);
                }
            }
        }
    }

    std::sort(candidates.begin(), candidates.end(), byStartTimestamp);

    for (LogicNote* note : candidates) {
        if (auto* tap = dynamic_cast<LogicTapNote*>(note)) {
            if (tryJudgePointNote(game, *tap, touch.id)) {
                return;
            }
        }

        // Hold acquisition path follows for non-point candidates.
    }
}

/*
 * Successful ArcTap path:
 *
 *   touch position qualifies child
 *       -> child enters sorted candidate list
 *       -> inherited point timing window
 *       -> ScoreState calls ArcTap successful-hit override
 *       -> child locally hit
 *       -> parent mode != 2 ?
 *             yes -> normal score counters + LifeBarState fan-out
 *             no  -> stop after local resolution
 *
 * Missed ArcTap path:
 *
 *   parent update walks +0x120 children
 *       -> unresolved child older than time+100 threshold
 *       -> ScoreState LOST path
 *       -> ArcTap locally lost
 *       -> parent mode != 2 ?
 *             yes -> normal LOST counter + LifeBarState fan-out
 *             no  -> stop after local resolution
 */

// -----------------------------------------------------------------------------
// 17. CONFIRMED / RECONSTRUCTED / UNRESOLVED summary
// -----------------------------------------------------------------------------

/*
 * CONFIRMED:
 *   - LogicArcTapNote derives from LogicTapNote.
 *   - parent LogicArcNote owns ArcTap children around +0x120.
 *   - parent path builder evaluates child timestamp through the Arc easing path.
 *   - child cached 12-byte path point is stored at ArcTap +0x80.
 *   - touch-begin spatially tests ArcTap children through their parent Arc.
 *   - hit-region helper receives nominal 212 and ArcTap mode flag 1.
 *   - qualified children enter the same temporary candidate vector as other
 *     input candidates.
 *   - candidate vector is sorted by note +0x18 timestamp.
 *   - ArcTap then calls the exact common point-note timing routine.
 *   - ArcTap successful-hit hook sets local hit and payload state.
 *   - ArcTap LOST hook sets local LOST state.
 *   - both hooks veto ScoreState only when parent +0xA4 == 2.
 *   - automatic ArcTap miss loop is parent-owned and uses > tapTime + 100 ms.
 *   - Arc initialiser promotes +0xA4 0 -> 1 when child vector is non-empty.
 *   - parent mode 1/2 disables ordinary Arc-body contact judgement.
 *   - no parent current-contact requirement exists for ArcTap point judgement.
 *
 * RECONSTRUCTED:
 *   - member name parentArc for ArcTap +0x90.
 *   - names ArcBodyMode / JudgedBody / NonJudgedBodyWithJudgedArcTaps /
 *     NonJudgedBodyAndSuppressedArcTaps.
 *   - friendly names cachedPathPoint and effectivePathEnd.
 *
 * UNRESOLVED:
 *   - exact original semantic name and higher-level purpose of Arc mode 2.
 *   - exact assignment site / original member name for ArcTap +0x90.
 *   - exact meaning of ArcTap string-like state around +0x98.
 *   - exact final ArcTap hit-region dimensions after camera/screen scaling.
 *   - exact semantic identity of the parent related-pointer vector +0x138 which
 *     can extend the path-evaluation horizon.
 */

// -----------------------------------------------------------------------------
// 18. Next narrow excavation target
// -----------------------------------------------------------------------------

/*
 * With Tap, Hold, Arc body, Arc path, and ArcTap now understandable, the one
 * surviving LogicNote subtype not yet given its own gameplay excavation is:
 *
 *   LogicFlickNote
 *
 * A sensible next slice is therefore:
 *   - what touch/gesture state qualifies a flick
 *   - whether it has a point timestamp or another interval representation
 *   - its timing window and direction/velocity threshold, if any
 *   - its success/LOST hooks into ScoreState
 *   - whether the surviving implementation is active modern gameplay code or
 *     historical/dormant machinery
 *   - stop before rendering
 */
